set nocp
syntax on
filetype plugin indent on
set number

set background=dark

set backspace=2
set tabstop=2
set shiftwidth=2
set expandtab

set wildmode=longest,list,full
set wildmenu

set splitbelow
set splitright

inoremap jj <ESC>

nmap <S-Enter> O<Esc>j
nmap <CR> o<Esc>
